Remove symkey deletion
WalletConnect/push-client-js pull request #40
Opened 2023-08-22 08:29 UTC by devceline

2023-08-22 15:35 UTC, bkrem requested changes
Great catch thank you 🙏 not quite ready to merge yet

2023-08-22 15:35 UTC, bkrem commented on packages/notify-client/src/client.ts
> +        this.core.crypto.setSymKey(subscription.symKey, subTopic).then(() => {
Is this related/still wanted?

2023-08-22 15:35 UTC, bkrem commented on packages/notify-client/src/controllers/engine.ts
> +    console.log(
Debug log

2023-08-22 15:35 UTC, bkrem commented on packages/notify-client/src/controllers/engine.ts
> +        console.log(
Debug log

2023-08-22 15:35 UTC, bkrem commented on packages/notify-client/src/controllers/engine.ts
> +        console.log("Decoded: ", payload);
Debug log

2023-08-22 15:35 UTC, bkrem commented on packages/notify-client/src/controllers/engine.ts
> +  private resolveDappPublicKey = async (
The method name is misleading now if we return two distinct keys, we should rename in this case:

```suggestion
  private resolveDappKeys = async (
```

2023-08-23 08:20 UTC, devceline commented on packages/notify-client/src/client.ts
> +        this.core.crypto.setSymKey(subscription.symKey, subTopic).then(() => {
Yes - doesn't hurt to have it

2023-08-23 08:20 UTC, devceline commented on packages/notify-client/src/controllers/engine.ts
> +    console.log(
Keeping logs for now as they're needed for testing

2023-08-23 08:39 UTC, bkrem approved these changes
Build is failing bc the method callsites need to be updated still to the proper naming

2023-08-23 08:55 UTC, merged